### ISSUE TITLE
Fix Facebook's OG image tag

### ISSUE THREAD

**Issue by rudimk** [hasgeek/funnel#100]
Currently, when a Funnel link is shared on Facebook, Facebook's Open Graph parser reads ```<og:image>``` tags, to pull an image to display on the post, for the link. Unfortunately, the image isn't being resized correctly, when shared in this manner.

**Comment by shreyas-satish** [comment]
Fixed.

![funnel_og](https://cloud.githubusercontent.com/assets/380688/5626779/00c9d8da-95b6-11e4-9489-c2fa30550907.png)

Thanks @karthikb351
