### ISSUE TITLE
A page which would contain the documentation and guidelines for the speakers

### ISSUE THREAD

**Issue by djamg** [hasgeek/funnel#1001]
Currently, guidelines are sent to the speakers as a pdf file attached to the mail. Can there be a permanent place for this on the platform which would be visible only to the project-crew/speakers?

**Comment by jace** [comment]
Suggestion: create an `av` project under the `hasgeek` organization and add the documentation as submissions. Markdown is a fairly powerful markup language and should have everything you need.

**Comment by jace** [comment]
Or it could even be a `help` or `doc` project.

**Comment by jace** [comment]
I think we should have one documentation project per service offered, so AV and ticketing should be separate projects.

**Comment by jace** [comment]
Closing this ticket since we're using the help org+project approach.
