### ISSUE TITLE
Add markdown rendering for text in preview of next/upcoming sessions 

### ISSUE THREAD

**Issue by banbreach** [hasgeek/funnel#1023]
![preview](https://user-images.githubusercontent.com/37100874/107215495-624bab00-6a31-11eb-8b07-25e02f0cf6f9.png)

**Comment by jace** [comment]
New preview filter added in https://github.com/hasgeek/baseframe/pull/345. Should be used here soon.

**Comment by jace** [comment]
Resolved in #1055.

![Screenshot of text preview](https://user-images.githubusercontent.com/26695/112864792-cb68aa00-90d5-11eb-874b-be530e5723ca.png)
