### ISSUE TITLE
Private comments for EP

### ISSUE THREAD

**Issue by rudimk** [hasgeek/funnel#105]
We need a system, where every proposal has different types of comments, based on access roles: there are public comments, which are viewable by the public; then there are private comments, which are only visible to members of the editorial panel, and the owners of that particular proposal space.

EP members usually are part of the Reviewers team on Lastuser. We could have a switch that's displayed only when a Reviewer/Owner's logged in, that enables the EP to set the visibility level of a particular comment.

**Comment by jace** [comment]
Merging with #94.
