### ISSUE TITLE
Style guide for @reopen decorator

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#1053]
The `reopen` decorator is often used like this:

```python
@reopen(User)
class User:  # type: ignore[no-redef]  # skipcq: PYL-E0102
    ...
```

While the `User` class here appears to be redefined, it isn't actually, as `reopen` returns the original class with the added elements, discarding the new class. However, linters (here mypy and PyLint) cannot identify the activity of the decorator and raise a warning, and therefore need explicit suppression.

It may help to use an underscore-prefixed private name for the temporary class, like this (we'll need to test for implications of double underscored vs single underscored):

```python
@reopen(User)
class __User:
    ...
```

This change will need to be applied to all current and future uses of `reopen`.

**Comment by iambibhas** [comment]
Don't have much opinion about it. If the name doesn't matter, can it be just `class __:`?

**Comment by jace** [comment]
`__` is the gettext function, plus we'll get a redefinition warning if they are two reopens in the file.
