### ISSUE TITLE
Max password length

### ISSUE THREAD

**Issue by chirayudesai** [hasgeek/funnel#1056]
I noticed that there's a max password length and it's set to 40 characters (Added in #617)

Is there a particular reason to have a maximum?

I had my password manager set to a longer string and that tripped on this, 40 is plenty in any case I imagine but I'm just curious if there's a reason to enforce a max length.

**Comment by jace** [comment]
It has no impact on our hashing algorithm. We capped it to prevent arbitrarily large passwords, like several kilobytes in size. What size do you use?

**Comment by chirayudesai** [comment]
Thanks, I had mine at 63/64.

Works now.
