### ISSUE TITLE
Private comments between the EP and a proposer

### ISSUE THREAD

**Issue by rudimk** [hasgeek/funnel#106]
A follow-on from #105 - this is for enabling conversations between the editorial panel, and a proposer, and thus make Talkfunnel more conducive for content moderation. In this case, there could be another switch of sorts, that will enable an EP member to define if a particular comment should be visible to the proposer. In the same manner, there'll be a switch available at the proposer's end, to define whether a comment is public, or only visible to the EP.

One caveat here, is that proposers aren't usually given any team per se, the way the EP is assigned one. In this case, we'd have to check against the proposer, in order to fix visibility levels.

**Comment by jace** [comment]
Merging with #94.
