### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by rudimk** [hasgeek/funnel#107]
Building on top of #105 and #106, it would be neat, having notifications for new comments being posted, between the EP, as well as between the EP and a proposer.

In the case of EP-only comments, an email can be fired off to every EP member, whenever one of them comments on a proposal. When it comes to EP+proposers, the proposer is sent an email too. This should help the EP - and proposers, when relevant - keep track of the conversation around the editorial process for a talk, and thus streamline putting together content for an event.

**Comment by jace** [comment]
Deprecated in favour of #605.
