### ISSUE TITLE
Funnel - Additional column indicating tools which will be showcased/used

### ISSUE THREAD

**Issue by gnot** [hasgeek/funnel#11]
Scenario - An attendee decides to attend a session based on speaker, description of session and tools/techniques. We capture speaker name, description. It would be good to have tool column too. 

Impact - 
1. For every event a metadata of tools needs to be created to prevent misspellings. 
2. Proposal creation needs to have this "required" choice - which indicates just talk or tools usage demo.  This is specially pertinent in BigData as the eco-system is vast. In case of metarefresh - it could be easier. Tools for development(e.g., editor), tools of the trade(domain specific e.g., R Studio or GATE toolkit)
3. View of the schedule needs to have this display column with possibility of "hiding ability". Say in dedicated workshop like cartographer stuff - it was apparent whole workshop is around tools/process of certain kind.

**Comment by jace** [comment]
Proposals have moved to being plain text fields, with additional metadata support such as labels. It's been a while and this ticket was forgotten. Closing it now.
