### ISSUE TITLE
Funnel - Schedule view should have physical seperation of type of sessions

### ISSUE THREAD

**Issue by gnot** [hasgeek/funnel#12]
Context - Although funnel has column of indicating type (tutorial or part of workshop vs a talk). Will it be possible to have “physical separation” plus indication of “possible date”.   Even if there is table based background color seperation or 2 rows between "grouped" sessions - it will be clear on eye and absorption. 

Impact - I guess a filtered query will need be issued for each types of sessions and results need to be bound. It might have impact on the "sorting" which has been implemented.

**Comment by jace** [comment]
Closing as this is obsolete. Schedule view now shows columns per room (pre-pandemic!), and everything is online anyway in 2021.
