### ISSUE TITLE
Add Twitter cards with a link to the app

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#121]
Proposals should have a Twitter card with a summary. All pages should have an app install Twitter card linking to the Talkfunnel app.

**Comment by karthikb351** [comment]
@jace You want to do content summaries? You prefer linking to the app?

Moreover, I think this makes more sense once the app is ready, and we can do deeplinking.

**Comment by jace** [comment]
Can't you do both?

**Comment by jace** [comment]
This was unintentionally closed because of the repo merger of Lastuser into Funnel. However, since Twitter cards have been present for a while and the native app is discontinued, I'm considering this closed.
