### ISSUE TITLE
Offline support for check-in

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/funnel#136]
Event check-ins currently depend on the internet at the venue being functional. If the internet is down, the check-in personnel either have to tether internet from their phones (which can be quite flaky) or in the worst case, write down names of participants in a text editor. There are two solutions to this:
1. [Build an app](https://github.com/hasgeek/zalebi/issues/9) that is dedicated to check-in participants. This approach won't work when an event does not have badges for its participants. A related question to ask - can participants self check-in?
2. Make the check-in views offline capable. React and PouchDB seem like good options to go with, to build an offline-capable check-in page.

**Comment by jace** [comment]
Closing as there is no demand for this feature in the pandemic era.
