### ISSUE TITLE
Introduce prismjs

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/funnel#1515]
The new markdown parser already renders out-of-the-box HTML5 style markup (with the `language-*` class) for fenced blocks.

prismjs activates styling for `language-*` blocks with it's autoloader, which we will utilise.

**Comment by jace** [comment]
prismjs should replace Pygments for code syntax highlighting. While this will introduce per-render load to the client side, it is better integrated into the page view experience and doesn't interfere with HTML sanitization.

Pygments is one of the main reasons we don't allow inline HTML — our sanitization removed all the Pygments highlighting as user-specified CSS classes are not allowed.
