### ISSUE TITLE
Add support for Chrome web app install banners

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#160]
Chrome now has a well defined process for showing an app install banner within the browser. We should support this. https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android

The document describes how both web app and native app banners can be displayed.

**Comment by sindhus** [comment]
From the linked page:

>Why do I need a service worker?
>We believe that when you add to the user’s home screen you should be providing an app-like experience. A service worker, especially one that supports push messaging or offline, is a strong indicator that you are developing a first class device experience. We recommend the following simple Service Worker as a starting point.

Do we have a service worker? I don't know what that means hence the question. 
I'd like to take this up.

**Comment by jace** [comment]
We don't have a service worker. We need one.

**Comment by jace** [comment]
@sindhus I'll recommend taking on something simpler. Service workers aren't trivial.

**Comment by jace** [comment]
This has been resolved for a while as we're now a PWA.
