### ISSUE TITLE
In the Proposal Model, change Objective and Description to Abstract and Outline

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#163]
The "Objective" and "Description" sections of the `Proposal` model have served us well over the years, but it's time to move on. "Abstract" and "Outline" are better descriptors for how we'd like people to submit proposals now.

However, we can't apply these new labels to previously submitted proposals, so I propose we add a `labels JsonDict` to `ProposalSpace` instead. The template for rendering a `Proposal` (and proposal form) will consider these labels and use them instead.

We can start referring to the two columns as "Part A" and "Part B" (or "First Part" and "Second Part") in the admin UI, and in the migration set all existing proposal spaces to use the "Objective" and "Description" labels, while all new proposal spaces get default values "Abstract" and "Outline".

This ticket conflicts with #109, which presents a more ambitious plan and should eventually be implemented, replacing this one when the time comes.

**Comment by shreyas-satish** [comment]
Fixed in https://github.com/hasgeek/funnel/pull/164
