### ISSUE TITLE
Project crew should be allowed to have custom role names

### ISSUE THREAD

**Issue by zainabbawa** [hasgeek/funnel#1665]
Project crew is currently designated as editor, promoter and usher. This is visible to everyone. It is creating confusion because someone who is, say, helping a workshop instructor to curate their content, is mistaken to be the workshop instructor.

It should be possible to add a custom role name to clearly identify the role that each individual has. For example, for a workshop project, the instructor should be able to create a custom role such as "workshop instructor". Those to give feedback to the instructor can be designated as reviewers. 

This may in turn cause confusion for editors because the label is not the actual role. A label sticker can be applied to indicate an explicit role in addition to the system recognized access rights. The actual access rights should not be hidden.

**Comment by jace** [comment]
Labels can now be assigned to crew members and are displayed alongside their names. There is no change to how roles are processed and displayed, so there remains some ambiguity over what those terms mean (Editor, Promoter, Usher).

<img width="742" alt="Crew label screenshot" src="https://user-images.githubusercontent.com/26695/225139547-f4bfb8d3-2123-4544-80d8-9e43967086b4.png">

**Comment by jace** [comment]
These custom labels are currently _not_ displayed in comments, where role-based labels continue to be used.

**Comment by jace** [comment]
There is no support for custom ordering of names. Currently, any role or label change will push the name to the bottom. We have to make a choice:

1. Names are ordered alphabetically
2. Names are ordered by implicit hierarchy based on the roles (Editor above Promoter or other way?)
3. Names are ordered by the label, alphabetically
4. Names are custom-ordered with drag and drop support — which has potential to cause intrigue about why they are ordered in a specific way

**Comment by zainabbawa** [comment]
Since I create implicit hierarchies, my choice is custom-ordered with drag and drop.

**Comment by zainabbawa** [comment]
Based on feedback from GenerativeAI community, the vote for ordering is for #2 - Names are ordered by implicit hierarchy based on the roles (Editor above Promoter or other way?). @jace
