### ISSUE TITLE
Participation certificates for event attendees

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/funnel#170]
Participants sometimes ask us for participation certificates, for having attended our events. Since, `talkfunnel` now has a check-in system, the system can check if a participant has indeed attended an event, and, in turn, mail them their participation certificate. There are different types of requirements that need to be satisfied for this feature to go live:
### Design
- We need a design template, that can be customized to fit the logo of the respective event.
### Policy
- We need to chart out our policies on customer service. For instance, what happens when somebody contests that they have indeed attended an event, when our records suggest otherwise? 

Hat tip @jace for this point.
### Technical
- The design template has to be converted to a HTML/CSS template.
- An option to 'Send Participation Certificate' should be added on the check-in dashboard, for each participant. The button should trigger an email to the participant, with a link to their certificate.

**Comment by jace** [comment]
Closing as there is no demand for this in the pandemic era.
