### ISSUE TITLE
Shortlinks generated in UI need a way to incorporate additional tags

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#1738]
When a shortlink is generated through the "Share" interface in UI (either webshare, or share from the custom menu which has copy, email, social etc), the shortlink includes the URL and specific UTM tags: `utm_source` (`webshare` or `share-*`) and `utm_medium` (`email` or `social` if not using webshare). There is no facility to use other UTM tags such as `utm_campaign`, nor for any other form of tagging.

This requirement of additional tags is not generic, and therefore not necessary for all users. However, it is a definite requirement for internal use. This issue is for discussing possible solutions.

**Comment by jace** [comment]
**Option 1:** If the user is a site editor, the "share" option will open a modal and allow customisation of tags. This will avoid burdening everyone else.

1. 👍 This will solve the problem without complicating UI for everyone else
2. 👎 Site editors will no longer have the same experience as regular users, making it harder to communicate workflow
3. 👎 Non-site editors may need the feature too
4. 👎 Automated testing will become complicated as there are two variants of the workflow; some tests will explicitly describe workflow for a site editor, while other tests will have to contend with not knowing whether the user is a site editor or not, but the test must work for both types

**Comment by jace** [comment]
**Option 2:** No change in UI, but if the loaded URL has any tags, they will be copied into the generated short link.

1. 👍 Almost no technical overhead in implementing this
2. 👍 The feature can be accessed by any user as there's no gatekeeping
3. 👎 The feature is not discoverable as there's no UI, so target users will need specific training
4. 👎 The URL is not editable when using a mobile PWA
5. 👎 Ad blockers also have UTM tag strippers that will interfere with such manually edited URLs

**Comment by miteshashar** [comment]
> **Option 2:** No change in UI, but if the loaded URL has any tags, they will be copied into the generated short link.

Another downside this option has is that it will possibly populate our analytics platforms with numerous unwanted campaigns.

**Comment by jace** [comment]
**Option 3:** A separate page for generating short links with custom tags.

1. 👍 Since it's a distinct flow, it does not change existing user flow and automated testing in any way
2. 👍 This page can perform necessary validations to prevent misuse (junk tags) or unauthorised use (restricted users)
3. 👎 To use, user must first copy the URL to shorten, then arrive here and paste it, adding a few steps to their flow

**Comment by miteshashar** [comment]
> **Option 3:** A separate page for generating short links with custom tags.
> 3. 👎 To use, user must first copy the URL to shorten, then arrive here and paste it, adding a few steps to their flow

If we can define authorised use, we could just have an extra link in the share menu that redirects to this page, taking away the pain to manually copy paste the link, which could in rare cases be prone to error.

**Comment by pakodatriestech** [comment]
> 

utm_campaign may be needed - since now we are taking a campaign approach.

**Comment by miteshashar** [comment]
> > **Option 3:** A separate page for generating short links with custom tags.
> > 3. 👎 To use, user must first copy the URL to shorten, then arrive here and paste it, adding a few steps to their flow
> 
> If we can define authorised use, we could just have an extra link in the share menu(for the authorised users) that redirects to this page, taking away the pain to manually copy paste the link, which could in rare cases be prone to error.

@jace How is authorized use defined?
