### ISSUE TITLE
API for mobile and client apps

### ISSUE THREAD

**Issue by karthikb351** [hasgeek/funnel#174]
### Required routes

`<space>/sessions/json`: A list of all sessions
`<space>/participants/json`: A list of all participants
`<space>/participant/exchange` (with auth): Endpoint to exchange puk+key for contact data
`<space>/proposal/{id}/feedback` (with auth): Endpoint for submitting feedback for a talk
### Flattened schedule

Right now both `/json` and `/schedule/json` give a result in the format of 

``` json
{
   "proposals": [],
   "schedule": [
    {
      "date": "2016-11-10",
      "slots": [
        {
          "sessions": [
            {
              "description": "",
              "description_text": "",
              "end": "2016-11-10T04:15:00Z",
              "feedback_url": null,
              "id": 27,
              "is_break": true,
              "json_url": null,
              "proposal": null,
              "proposal_url": null,
              "room": null,
              "section_name": null,
              "section_title": null,
              "speaker": "",
              "speaker_bio": "",
              "speaker_bio_text": "",
              "start": "2016-11-10T03:15:00Z",
              "technical_level": null,
              "title": "Check-in and breakfast",
              "url": "https://droidconin.talkfunnel.com/2016/schedule#27-check-in-and-breakfast"
            }
          ],
          "slot": "08:45"
        },
      ]
    },
    ]
}
```

This is too verbose to parse, it would be great to just get a list of sessions for a proposal space.

**Comment by jace** [comment]
Closing as this is obsolete. There is slow progress towards a full GraphQL API, but for now most endpoints support JSON.
