### ISSUE TITLE
Voting should use POST not GET

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#175]
In [views/commentvote.py](https://github.com/hasgeek/funnel/blob/45269a53084c8f1aeb4caf30b52d2831a1066eda/funnel/views/commentvote.py#L11), the `voteup` and `votedown` endpoints should use POST not GET. This has been in FIXME status for years.

**Comment by harshalbhatia** [comment]
Was looking into doing this but cee20d7c4f50cef70a67c938542c87fb338a11a7 already resolves this. Does more need to be done?
