### ISSUE TITLE
Proposal comments should go to everyone who participated

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#181]
There are pending special-case notification tickets in #105 (private notes), #106 (private comments) and #107 (notifications). While those remain relevant, we need a quick fix for something that affects users currently:

When someone leaves a comment on the proposal, and someone replies, there's a tendency to reply top-level instead of to the comment. Top level comments send an email notification to the proposer only. In case it is the proposer who is replying, nobody gets a notification. This breaks editorial workflow because reviewers need to look at each proposal for new replies.

1. Funnel should not show a top-level comment box or button below existing comments. The label should indicate who gets notified when a comment is left.

2. Users should get a "comment notifications" option on each proposal, visible in the UI. A user can be in the notifications list with an explicit option of yes or no, or also missing from the list, in which case defaults apply (for example, when `@mentioned`).

3. Notifications go to everyone who has notifications enabled, not just in the thread.

4. An `@mention` should send a one-time email notification to that user, without subscribing them to the thread.

**Comment by shreyas-satish** [comment]
> Funnel should not show a top-level comment box or button below existing comments.

Where should it be moved to?

**Comment by jace** [comment]
Show it only when the comment link/button is clicked.

**Comment by shreyas-satish** [comment]
> A user can be in the notifications list with an explicit option of yes or no, or also missing from the list

By 'yes', does this mean that the user gets notified of _all_ the comments posted for a proposal? And by 'no' does it mean that the user does NOT get notified of _any_ comments, even if mentioned?

**Comment by jace** [comment]
We could use the GitHub model: Default not watching (except when @mentioned), watching (all comments) or muted (no alerts).

**Comment by shreyas-satish** [comment]
Working on this. Does it make sense for the proposer's default to be 'all'?

**Comment by jace** [comment]
Yes. You need a subscription table where "default not watching" status implies user isn't in the table, and the other two states are set with a flag. Proposers get added to the table just like their own upvote is added.

**Comment by jace** [comment]
Merging this into #605.
