### ISSUE TITLE
Notify proposers to submit slides and video

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/funnel#183]
This is as per the discussion with @zainabbawa.

Funnel should make it possible for an editorial workflow to mandate the submission of slides and a video for submitted proposals. An editorial team should be able to set a deadline date for the submission of slides and video. Consequently, funnel should send periodic reminders to proposers who have not submitted their slides and video as part of their proposal.

Further, funnel should mark the proposals which have slides and video submitted, with icons (as is done with outstation speakers). This will help an editorial team to quickly assess the status of slides and video submission in aggregate.

**Comment by jace** [comment]
Closing as this is obsolete. We've moved to a less rigid workflow overall.
