### ISSUE TITLE
Twitter Cards

### ISSUE THREAD

**Issue by harshalbhatia** [hasgeek/funnel#186]
Many Hasgeek websites don't currently support Twitter cards. Adding this would be great for word of mouth.

I understand we currently tweet with an image, but that's a very small ___button___ for the user to click on. The large cards [1] attract attention like no other. Also, when users share the site then it's just the link.

I like Pieter Levels' implementation of this using Phantom.js [2]. He dynamically generates a card at regular intervals.

Created this issue to understand how high this is on the priority list. Would be glad to implement this.

[1] https://dev.twitter.com/cards/types/summary-large-image
[2] https://levels.io/phantomjs-social-media-share-pictures/

**Comment by harshalbhatia** [comment]
#121
Oops, there is already a twitter cards issue. But it comes at this from the app perspective. I don't know whether the app allows deep linking yet, but even just for the website i think this is worth doing.

**Comment by jace** [comment]
Closing because it's unclear if this is still an issue. We've had Twitter cards for a while.
