### ISSUE TITLE
Updating rooms in project venue throws a 401

### ISSUE THREAD

**Issue by anishTP** [hasgeek/funnel#1893]
### Context
The project editor tries to update the venue details from the project settings menu. 

### Problem
On delete or update room option the editor sees a 401 No authorization error code. The issue persists after the editor has promoter/usher roles added to their profile. The issue persists for project owners as well.

**Comment by jace** [comment]
We don't raise a 401 anywhere as it causes a browser login prompt. Do you mean 403?

**Comment by anishTP** [comment]
Sorry I meant 403.
