### ISSUE TITLE
Restrict characters in talk titles

### ISSUE THREAD

**Issue by booleanbalaji** [hasgeek/funnel#200]
Since funnel is our primary source of information about the talk, having a really long title causes problems when abstracting the information elsewhere. This leads to us copy-editing the title when using them in posters, badges and video titles. 

The following constraints can be added to the title field:

1) Restrict the number of characters to 50
2) Disallow use of special characters other than standard ones (prevent emojis)

**Comment by jace** [comment]
What's wrong with emoji?

**Comment by jace** [comment]
Closing as this is obsolete. Editors can control display via the Session model.
