### ISSUE TITLE
SSL Certificate error in Talkfunnel subdomain

### ISSUE THREAD

**Issue by ananyo2012** [hasgeek/funnel#202]
I tried to setup a Talkfunnel page for accepting proposals at https://pyconfhyd.talkfunnel.com/ . But I am getting an SSL certificate error similar to the image attached
![photo6078106132842391540](https://user-images.githubusercontent.com/10486343/29116377-356a47c2-7d18-11e7-8f86-49ca1089ad0b.jpg)
Can this be fixed?

**Comment by iambibhas** [comment]
Fixed https://pyconfhyd.talkfunnel.com/
