### ISSUE TITLE
Broken 'coaster' dependency

### ISSUE THREAD

**Issue by ultimatecoder** [hasgeek/funnel#205]
* **Description:** The [coaster][coaster] dependency versioned `0.6.dev1` is broken.

* **My Configuration:**
    * Operating System: Ubuntu 16.04 LTS
    * Python Version: Python 2.7.12
    * pip version: 9.0.1

* **Traceback:**
```
$ python manage.py db create
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from coaster.manage import init_manager
  File "/home/myuser/.virtualenvs/funnel_dev/local/lib/python2.7/site-packages/coaster/__init__.py", line 6, in <module>
    from .utils import *  # NOQA
ImportError: No module named utils
```

* **Why to not report at [coaster][coaster] and here?**
I believe the development version should not be linked to any project rather a released version should. Perfectly fine if it is the latest version. ~~I might supply a patch linking [coaster][coaster] from [pypi](https://pypi.python.org/) and not the GitHub repository.~~ Created PR #206 

[coaster]: https://github.com/hasgeek/coaster

**Comment by jace** [comment]
Please report coaster issues on coaster, not here. In HasGeek's repositories, the `master` branch is always stable, with development happening on other branches.
