### ISSUE TITLE
Redirect to previous URL upon logout

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#213]
Right now if you have a proposal page open and you logout, it redirects you to talkfunnel.com home page. I think it'll be much more useful if we just redirected people to the page they were on when they clicked the logout button.

**Comment by jace** [comment]
Redirect to home page is intentional, as the page they came from may only be available to a logged-in user, in which case they're shown the login page all over again. If anything, we need a mechanism by which to determine if it's safe to send the user back to where they came from.

**Comment by iambibhas** [comment]
so, if the previous view wasn't a login-required view, then send there, if not, send to home page. is it possible to find which views are login protected?

**Comment by jace** [comment]
We can't, because the `@requires_login` decorator is not queryable. While we can find the view function associated with a URL, there's no clean way to check if it requires login without calling it.

**Comment by jace** [comment]
Views now have an `.is_available()` method that solves query problem, and this is used in a number of places. Closing this ticket.
