### ISSUE TITLE
Disable proposal deletion/restrict edit for proposers

### ISSUE THREAD

**Issue by Callisto** [hasgeek/funnel#215]
Proposers constantly change their talk details and topics while they are under evaluation or even after confirmation. Often shortlisted proposals tend to disappear as well when the proposers want to withdraw their talks and end up deleting them and never inform the editors.

**Comment by jace** [comment]
@iambibhas Hard deletes should be replaced with soft deletes, using a status code.

**Comment by Callisto** [comment]
Is it possible to have history tracking on the proposals? It's hard to keep track of modifications users make every other day.

**Comment by jace** [comment]
That's a non-trivial technical change. It'll take months.

**Comment by Callisto** [comment]
Okay, never mind then.

**Comment by shreyas-satish** [comment]
One solution might be to let the review team approve edits. This way, the review team knows exactly what's being edited. This also helps them assess edits in a scenario where the review team has asked the proposer to make changes to the proposal.

**Comment by jace** [comment]
Variant of the same problem: we need to store multiple drafts and decide which version to display to whom. We've attempted to tackle this problem in both [Eventframe](https://github.com/hasgeek/eventframe/blob/796f9d3c1975eebbb9cc6de9298e84191a1fcf44/eventframe/nodes/content/models.py#L12), [Hasmail](https://github.com/hasgeek/hasmail/blob/284f3a879b16dddfa0adb54639af324440a2b353/hasmail/models/email.py#L140) and [Nodular](https://github.com/hasgeek/nodular/blob/16acb61da04beed22b173addc7c85abfc27b8c96/nodular/revisioned.py). The model is easy. The business logic is non-trivial.

**Comment by iambibhas** [comment]
@jace what needs to be done with this?
