### ISSUE TITLE
Ability to move a proposal to a proposal space under a different profile

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/funnel#216]
Current, funnel lets a proposal manager to transfer proposals from one proposal space to another, under the same profile. While this is useful, there's a requirement for moving a proposal to a proposal under a different profile too, given the proposal manager is allowed to manage proposals for the other profile too.

**Comment by iambibhas** [comment]
@shreyas-satish how do we decide which of the profiles does a proposal manager has access to?

Right now, it's decided like this - 
```
{%- for movespace in proposal.proposal_space.profile.spaces %}
    <li><a href="{{ proposal.url_for('move-to', target=movespace) }}">{{ movespace.title }}</a></li>
{%- endfor %}```

Seems like it doesn't check whether the user has access to other proposal spaces, or probably that `move-proposal` permission means that the user can move anywhere in that proposal space.

How do we find out which proposals a user has permission to move proposals to? Each profile has an `admin_team` property. So members of the admin team? Proposal spaces themselves again have an `admin_team` property. What is that for?

/cc @jace

**Comment by iambibhas** [comment]
@shreyas-satish I can instead just list all the ProposalSpace that has the current user in `admin_team`?

**Comment by shreyas-satish** [comment]
The business logic (in the `view) needs to prevent against a proposal being moved to a profile the user doesn't have access to. 

> I can instead just list all the ProposalSpace that has the current user in admin_team?

Can a user subvert the user interface and send a request that transfers a proposal to a profile they don't have access to? If yes, then this won't suffice.

**Comment by iambibhas** [comment]
@shreyas-satish ok. but right now there is no such check at all. If the user has `move-proposal` permission, then they can move to any proposal space of the current profile. I want to know the scope of `move-proposal` permission and how it's decided.

**Comment by shreyas-satish** [comment]
https://github.com/hasgeek/funnel/blob/master/funnel/models/space.py#L194

**Comment by iambibhas** [comment]
@shreyas-satish ah. same logic. thanks.
