### ISSUE TITLE
Funnel Session Proposal Screen Enhancements

### ISSUE THREAD

**Issue by arg0s** [hasgeek/funnel#22]
I'd like to propose a few minor enhancements to the 'Submit a session proposal' screen:
1. Provide the section outlines inline. While it is accessible from the funnel page, it is relevant and in context here.
2. a. I suggest we change the verbiage around slides to indicate that providing a link to your slide draft will greatly enhance the likelihood of your getting community votes, reviews by the Program Committee & confirmation. 
3. b. If there's an option to provide a private slide link which is visible only to the Program Committee in case there are some elements of surprise in the content which the speaker may not want to expose upfront, that would be nice.
4. When a community member wants to propose a topic for someone to speak about, the page displays the same fields as those that need to be filled by a session speaker. I suggest hiding the fields that are not mandatory.
5. Can we request a link to a public profile source for the speaker bio through which we can use their picture for printed speaker bios?
6. It'd be nice to provide 'ghosted' example text for a few of the fields so that there's a reference point about what is expected. This of course would disappear upon input.
7. Lets ask the speakers if they have any special requirements for their setup?

I'm going to file a separate backlog ticket to track another feature where can request some of this information from the speakers after their initial confirmation by the Program Committee so that the initial proposal process doesnt get too long winded.

**Comment by jace** [comment]
This ticket was duplicated in #437 and resolved in #979. It's been a while!
