### ISSUE TITLE
Participant upsert leads to empty details

### ISSUE THREAD

**Issue by shreyas-satish** [hasgeek/funnel#221]
This was originally reported by @captn3m0 here - https://github.com/hasgeek/boxoffice/issues/209.

This is an issue with how `upsert` is currently managed by `Participant`. Essentially, if you buy a new ticket with the same email, the existing participant details are 'upserted' i.e the details of the participant are updated with the details entered in the new ticket.

The system should not update details that were _not_ provided.

**Comment by jace** [comment]
Closing as this is not a current problem with the way tickets are sold. The sync models are pending deprecation.
