### ISSUE TITLE
Add Program Committee Voting Features

### ISSUE THREAD

**Issue by arg0s** [hasgeek/funnel#23]
Right now, bulk of the work of going from the "pipe" that the funnel currently is to the narrowed down list is done manually by the Program Committee.  This ends up being a massive operational time sink in coordinating and following up on various things, while the committees time would be best served focusing on ensuring the best content is selected for the conference.

I suggest adding the following features:
- Ability tag a set of users as being a part of the program committee
- Counting their votes separately with a multiplier
- Ability to limit the number of entries committee members can vote against, since their role is only to steer and influence with a light hand.
- Ability to tag proposal 'state' as it pertains to where it is in the 'funnel' as entries go from the mouth to the stem.
- Enable notifications to the proposer about changes in proposal state.
- Ability to make PC votes publicly visible after a review period (so as not to initially bias community voting).
- Ability to inspect the number of community votes that a proposal has receive and see what % of those are from either a) members registered for the current conference, b) members who have registered for past conferences. 
- Rolled up funnel view that combined community and committee votes and stack ranks proposals. (Right click to change proposal review state on this screen would be handy)
- Veto ability if 2 or more committee members believe a certain speaker has gamed the system or violated conference terms and conditions.

**Comment by jace** [comment]
Committee-voting functionality was added via user groups several years ago, but removed in 2019 as our needs have changed. Closing this ticket since we'll need new tickets for everything we've learnt between 2012 and 2019.
