### ISSUE TITLE
Add a second Flask app

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#230]
To support the transition from Talkfunnel.com to HasGeek.com, a second Flask app should be added to Funnel, to support a different set of routes for the HasGeek website:

1. [x] Rename `app` to `funnelapp` since Talkfunnel will be the legacy site
2. [x] Add `runfunnel.py` that imports `funnelapp` as `application` instead of `app`
3. [x] Likewise, `funnelwebsite.py` for WSGI
4. [x] All modules importing app should import `app, funnelapp`
5. [x] All _current_ instances of `@app.route` should be replaced with `@funnelapp.route`
6. [x] A new set of `@app.route` rules should be added to the same views, with `<profile>.website.tld/<space>` becoming `website.tld/<profile>/<space>` (originally introduced in #102)
7. [x] Disable the `/new` route for `funnelapp`
8. [x] All run-time references to `app` should change to `current_app`
9. [x] Audit for extensions that can't handle multiple apps (Flask-Lastuser can't handle multiple Lastuser key/secret pairs, and Lastuser will be fussy about the website URL, so a ticket to fix that is necessary, maybe by accepting config as `init_app` parameters instead of retrieving from `app.config`)
10. [x] The layout template should render a different header (HasGeek or Talkfunnel logo) depending on which app is rendering, so this flag should be inspectable somewhere
11. [x] Profiles should be linked to just one of the apps via a flag (existing profiles go to Talkfunnel, new profiles go to HasGeek, and existing HasGeek profiles are migrated manually). This requires a migration
12. [x] If a URL is accessed from the wrong app, it should be redirected to the corresponding endpoint at the other app, so a before_request handler is required to intercept and examine (but can it return responses?)

**Comment by jace** [comment]
Simpler migration path: just deprecate Talkfunnel, offering current users a static site or an export to other proposal selection websites such as papercall.io.

**Comment by iambibhas** [comment]
> Disable the `/new` route for funnelapp

Can't just comment those routes otherwise the templates will fail wherever those urls are needed.

**Comment by iambibhas** [comment]
also, need different sets of settings file for both apps.

**Comment by jace** [comment]
> If a URL is accessed from the wrong app, it should be redirected to the corresponding endpoint at the other app, so a before_request handler is required to intercept and examine (but can it return responses?)

Since URL structures are changing, `before_request` can't rewrite the URL as it doesn't yet know which view will process it.

Instead, we have to update all the landing page views (Profile, Project, Proposal, Schedule) to do this redirect. If we switch to ClassView, it'll be easier to enforce this across more views.

**Comment by iambibhas** [comment]
> If a URL is accessed from the wrong app, it should be redirected to the corresponding endpoint at the other app, so a before_request handler is required to intercept and examine (but can it return responses?)

We're doing this inside a view decorator, in `views/decorators.py`. It makes use of `app.app_context()` and `app.test_request_context()` both to create url for the other app and then redirects to it. This is not an official way of doing it. Flask doesn't actually support cross-app poking like this. Details - https://github.com/pallets/flask/issues/1412
