### ISSUE TITLE
Strip trailing hyphens when constructing slugs for proposals

### ISSUE THREAD

**Issue by anandology** [hasgeek/funnel#231]
URLs like the following with trailing hyphens look odd. 

https://fifthelephant.talkfunnel.com/2018/36-building-scalable-machine-learning-pipelines-with-

It might be a good idea to strip hyphens when constructing the slugs.

**Comment by jace** [comment]
Since URL slugs are stored in the database, current URLs with trailing slugs will lose them the next time the proposal is edited. We only look up the leading number (36 in this case) when retrieving the item, so the URL change won't impact permalinks.

**Comment by anandology** [comment]
Awesome!
