### ISSUE TITLE
Event Schedule Management

### ISSUE THREAD

**Issue by arg0s** [hasgeek/funnel#24]
IMO, this can be built completely independent of the funnel either as a standalone service or on top of services like Trello who provide excellent APIs, but you guys know best so I wont get into the how.
- Ability to pick from pre-defined event calendar templates. For instance 1-day, 2-day, variants with 30, 45 min slots, etc. It would be ideal to be possible to change the template at any time, with a preview of conflicts that need to be resolved.
- Ability to drag and drop, Trello style from a stack list of the latest view of confirmed funnel entries into schedule tracks.
- Ability to tag volunteers to the individual tracks or rooms for infrastructure & logistical needs.
- Ability to view the schedule in 1-column, 2-column and 3-column layouts.
- Ability to export to ICS format may be handy, but I'm not yet totally sure it will be used a lot.
- The final event schedule that is published/printed/displayed should include # votes received from Community & Committee. I've noticed that attendees otherwise gravitate towards talks based on how salesy their title is since they cant get into the details from a printed sheet.

**Comment by jace** [comment]
Closing this as most of the relevant functionality was introduced in #64 and #65, with additional support for tagging individuals to roles arriving via #371.
