### ISSUE TITLE
Project date and location should not be a text field

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#287]
Location can remain a text field, processed like on Hasjob to identify location tags. The display date should be auto-calculated from the existing start and end fields. The existing date and location field needs to be (a) renamed or (b) deleted. Either case will involve manually editing the value for the existing 150+ projects.

**Comment by iambibhas** [comment]
I tried to clean up the existing `datelocation` values, and there are some issues(either missing dates or location) - https://gist.github.com/iambibhas/a2f2e94dcbd48da6c1be6d17b7afb303

In one case there are 2 dates in same project

**Comment by jace** [comment]
Where are these various columns from? Which are in the db, and which are the new ones you're making?

**Comment by iambibhas** [comment]
@jace they are from the `project` table. I added existing/new tags for each column. Check now.

**Comment by jace** [comment]
We have to retain the `date` and `date_upto` fields, but correct the values from the `datelocation` field. Don't bother with `date_raw`.

Are `date` and `date_upto` of type date or datetime? That will be a problem too.

**Comment by jace** [comment]
The location part moves into the `location` field and the `datelocation` field is to be dropped (two migrations, with manual data movement between them).

**Comment by iambibhas** [comment]
`date_raw` is more like a temporary field I kept to parse the dates from, and verify after parsing. It wont get in DB.

`date` and `date_upto` are of type `date`. `date` field doesn't seem to have anything to do with the dates of the project, even though the form says "Start date" for it.

**Comment by jace** [comment]
We don't display the date field. It's currently used for sorting. However, we will now start displaying it.

**Comment by iambibhas** [comment]
What is `date_upto`? I was thinking that it's the end date of the project. And it's the same as my calculated `to_date` almost in all case, except few. 

<img width="427" alt="screen shot 2018-11-23 at 3 32 28 pm" src="https://user-images.githubusercontent.com/357253/48937730-0ae6c080-ef35-11e8-9550-11809398f0e5.png">

3 fields above are `date`, `date_upto` and `datelocation`. `date_upto` doesn't match the end date of project. 

I was thinking about adding 3 new fields - `location, date_from, date_to`. Then thought that `date_upto` already has end dates, so maybe I can skip `date_to`. But now this inconsistency is making me rethink.
