### ISSUE TITLE
URL fields need to be 2000 characters long and should not be named just `url`

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#294]
A number of URL fields across models have variable lengths. The length needs to be standardised to 2000 characters. Also, the field should not be named `url` as that conflicts with hasgeek/coaster#193 (see hasgeek/coaster#200 for conflict details).

**Comment by iambibhas** [comment]
PR #298 sets all the existing URL field instances to length 2000. There is no field named `url` in funnel, so closing this.
