### ISSUE TITLE
Deprecate permission check using g.permissions

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#299]
Funnel uses permissions a lot and checks for permissions in `g.permissions` every time. Permissions are also used in views. We need to replace `<name> in g.permissions` check with `current_auth.permissions.<name>`. Which also means we need to replace the `-` in permission names using `_`.

**Comment by iambibhas** [comment]
The only use of `g.permissions` is now here https://github.com/hasgeek/funnel/blob/master/funnel/templates/comments.html.jinja2#L88

/cc @jace

**Comment by jace** [comment]
That requires this ticket to be resolved first: https://github.com/hasgeek/coaster/issues/211

**Comment by iambibhas** [comment]
`g.permissions` is no longer checked for permission anywhere in funnel. except few index views have `g.permissions = []` in them.

**Comment by jace** [comment]
Remove all references to `g.references` then.
