### ISSUE TITLE
More models need UUID columns

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#305]
We previously added UUID columns to Proposal and Session in #276. Turns out more models need UUIDs because they need public-facing keys:

* [x] Project
* [x] Profile (already has `userid`, a UUID in Base64 form)
* [x] User (likewise)
* [x] Team (likewise)

**Comment by jace** [comment]
One more needed:

* [ ] Comment

**Comment by jace** [comment]
@iambibhas Comment URLs use primary keys. They should use UUIDs instead.

**Comment by iambibhas** [comment]
Comments have UUID field now and use suid for urls https://github.com/hasgeek/funnel/blob/master/funnel/views/commentvote.py#L171

**Comment by iambibhas** [comment]
Added UUID to Comment in https://github.com/hasgeek/funnel/pull/324
