### ISSUE TITLE
Projects should support partial dates

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#317]
In case projects dont have a finalized dates at the time of creation, it should be possible to mention partial dates (e.g. Month and/or year only). Right now it's not allowed.

**Comment by jace** [comment]
We will be removing dates from projects as the next step after #355 (project states). That ticket makes CfP dates separate from project date. Next step, we'll add events to projects and have featured dates calculated from that.

**Comment by jace** [comment]
Deprecated by #383.
