### ISSUE TITLE
Move legacy URLs to Nginx config

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#323]
Funnelapp has some code to handle legacy `funnel.hasgeek.com/<project>` URLs (at the bottom of `views/index.py`). This code should be removed and redirects for these projects should be moved to Nginx config. The `legacy_name` attribute on the `Project` model should be dropped as well.

**Comment by iambibhas** [comment]
Nginx already redirects `funnel.hasgeek.com/<anything>` to `talkfunnel.com/<anything>` with `return 301 https://talkfunnel.com$request_uri;`.

**Comment by jace** [comment]
That's not what is required.

There is an optional `legacy_name` field in Project. Those specific names need to be redirected to the current URL for those projects.

**Comment by jace** [comment]
A naive redirect from Nginx will break those URLs as the redirects won't be valid.

**Comment by iambibhas** [comment]
I've added those redirects to nginx config. e.g. -
```
rewrite ^/jsfoo2011/(.*)$               https://jsfoo.talkfunnel.com/2011/$1    permanent;
rewrite ^/inboxalert/(.*)$              https://inboxalert.talkfunnel.com/2013-tentative/$1    permanent;
```

**Comment by jace** [comment]
Next task is a migration to remove the `legacy_name` column.
