### ISSUE TITLE
Changing dates for projects with scheduled sessions breaks schedule

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#349]
Right now changing a project dates doesn't update/move the scheduled sessions for that project. So as a result the scheduled breaks as the sessions being returned are not within the dates of the project (which is another bug).

So we need to either -
1. Restrict changing dates before all the sessions have been moved
2. Show warning that there are sessions already scheduled before dates are changed but not stop the user from changing, and then figure out a way to clean up the session table with the orphan sessions

**Comment by jace** [comment]
This is now resolved with #383 and #429.
