### ISSUE TITLE
Remove Project's date, date_upto and datelocation fields

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#383]
Project dates should be calculated from the schedule. We can offer cached fields to make queries faster, but these will be datetime fields, not date fields, so `date` and `date_upto` should be replaced with `schedule_start_at` and `schedule_end_at`.

Since the `date` and `date_upto` fields are used in UI for the schedule editor, this needs attention.

The `datelocation` field is also deprecated by the `location` field introduced in #287 and can be removed (data may need to be migrated).

**Comment by vidya-ram** [comment]
Workflow changes for schedule editor UI,
1. The schedule edit page will have a date picker. For projects with no sessions, the date picker will be set to current date and schedule calendar widget displays current day and two days after.
2. Sessions can be dragged and dropped into the schedule widget as before.
3. On selecting a different date from the date picker, the schedule calendar widget updates and shows the newly selected date and two days after.
4. The sessions added to a date still remain on those dates and can be viewed by the changing the date on the date picker.
5. On revisiting the schedule edit page, date picker and schedule calendar widget shows the date of first session and two days after.

**Comment by iambibhas** [comment]
`datelocation` model field was removed in #314.

**Comment by jace** [comment]
This decision was reversed in #1114 and projects again have a `start_at` and `end_at`. The difference now is that these fields are auto-updated from sessions, where sessions exist, but can also be set directly when sessions don't exist. This allows for lightweight projects where schedule details are unnecessary.
