### ISSUE TITLE
Defend against spam

### ISSUE THREAD

**Issue by balupton** [hasgeek/funnel#412]
I've noticed over the years, every few months, my talk proposals get hit by spam comments.

I'm not sure what spam defence mechanisms there in place, but setting up this thread to track them.

I would suggest putting cloudflare infront of the website, and turning their security level to high, to boot bots up before they even reach the server.

I'd also suggest using https://www.google.com/recaptcha/intro/v3.html so that for bots that get through to the server, their behaviour can be monitored and can be booted if it is robotic.

**Comment by jace** [comment]
We're taking a first pass at this in #413.

**Comment by jace** [comment]
@iambibhas Once hasgeek/baseframe#143 (invisible ReCAPTCHA) is done, the comment form needs a captcha field added.

**Comment by jace** [comment]
In #669 we introduced comment moderation and review. Anyone can now report a spam comment. Two moderators are then asked to look at it, and if they concur, the comment is removed. If they disagree with each other, a third moderator is asked to look at it. With this mechanism, we hope there is proactive review of spam and also a safety net when comments are incorrectly reported as spam.

We also went through the entire back catalogue and reported and reviewed all spam comments.

I'm marking this as resolved for now. Please re-open if there's anything else we can do to make it better.
