### ISSUE TITLE
Use rel=nofollow on proposal comments

### ISSUE THREAD

**Issue by captn3m0** [hasgeek/funnel#413]
Old proposals receive a lot of spam: https://hasgeek.com/50p/2018/proposals/the-secret-life-of-bank-codes-awBCMUFMW3zqqXERGtngGR

Setting a `rel=nofollow noindex` attribute should dis-incentivize spammers from doing this.

**Comment by jace** [comment]
@captn3m0 `nofollow` will be added to links in all new comments once hasgeek/coaster#226 is merged. We'll have to manually recompile existing comments since we cache them in the db.

Should we add `noindex` as well?

**Comment by jace** [comment]
It appears `noindex` only applies in the `<meta>` tag, not in `<a>` tags.

**Comment by captn3m0** [comment]
Yeah, just `nofollow` should be enough.

**Comment by jace** [comment]
Dependency is merged. Deployment and migration to follow.

**Comment by jace** [comment]
Done. All links in comments now have `rel="nofollow"`. We still need to remove the spam comments and add better filters, which I'll track in #412.
