### ISSUE TITLE
Withdrawn talks must be retained in the admin view

### ISSUE THREAD

**Issue by anandology** [hasgeek/funnel#43]
Today I got a complaint that the proposal count of PyCon India Funnel went down from 99 to 95. And there is no way to found out what happened by looking at the funnel.

Looking at the server access logs, I found that some entries were withdrawn, but it is too scary to have talks disappear like that. The withdrawn talks should be retained for admins or a log of events be maintained.

**Comment by jace** [comment]
Closing as this is obsolete.
