### ISSUE TITLE
Talkfunnel should not show projects from non-legacy profiles

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#432]
Talkfunnel currently displays all projects, sending users to `<profile>.talkfunnel.com/<project>`. For non-legacy projects, this page then redirects to the same page on hasgeek.com.

This is broken because talkfunnel.com does not have wildcard TLS certificates, and some profiles do not have their own TLS certificates.

Resolution:

1. Either get a wildcard TLS certificate for `*.talkfunnel.com`,
2. Or stop displaying projects from non-legacy profiles (recommended in the wake of the deprecation notice in #427).

**Comment by jace** [comment]
Currently broken link on talkfunnel.com: https://mec-dev.talkfunnel.com/conf/

**Comment by iambibhas** [comment]
I'm removing non-legacy profiles from funnel by passing `legacy=True` here - https://github.com/hasgeek/funnel/blob/49c4c0355c23e599d8db8b00bc2f8facfac208ee/funnel/views/index.py#L33

**Comment by jace** [comment]
Status? Now that wildcard subdomains are fixed?

**Comment by iambibhas** [comment]
Wildcards are fixed. But I'm still pushing this. Only showing legacy profiles on talkfunnel. That way the deprecation message is going to make more sense.

**Comment by iambibhas** [comment]
Fixed in ac4d09cc618748cf1b32bf35684b0f3c06c6e926.
