### ISSUE TITLE
Flash message placement and color

### ISSUE THREAD

**Issue by iambibhas** [hasgeek/funnel#457]
Flash messages on project page appear after the second navbar, in the middle of the screen. They need to go to the top of the screen. 

<img width="1162" alt="Screen Shot 2019-06-28 at 9 25 03 AM" src="https://user-images.githubusercontent.com/357253/60316080-d03f7d80-9986-11e9-9d04-b596d19f1110.png">

Also, without a category(`success`, `error` etc), the flash message background does not have a color. So it appears that it's just floating there among all the other text with a X button on extreme right.

**Comment by jace** [comment]
Additional issue: when logging in, the flash message confirming login appears on the second page after login, not immediately on the loaded page. I suspect this is because the home page is not rendering flash messages.
