### ISSUE TITLE
Schedule tab should be hidden if there is no schedule

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#458]
This project has a schedule tab. It doesn't need one. https://hasgeek.com/fifthelephant/the-fifth-elephant-round-the-year-submissions/schedule

The tab should be disabled if there are no sessions in the project.

**Comment by iambibhas** [comment]
This is already present. But schedule tab is shown to admins all the time. Public only see it if a published schedule exists.

**Comment by jace** [comment]
1. Remove for admins too.
2. Round the year projects have schedule state set to published incorrectly.

**Comment by jace** [comment]
Fixed in #462.
