### ISSUE TITLE
Comments with task lists

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#495]
Comments should support checklists similar to how GitHub does it:

1. Adding `[ ]` or `[X]` to the beginning of a list item should render it as a checkbox
2. These checkboxes should be clickable to toggle their state (this will count as an edit of the comment)
3. A count of checked vs unchecked items in the proposal and all its comments should be tagged onto the proposal and available as an attribute/property, for rendering wherever needed in templates

Issues to be settled:

1. This feature will most likely be used by reviewers to post a checklist for proposers to follow. The count of checked vs unchecked item is critical for review and checklists from public commentators will mess with the counts.

2. Who is allowed to check off an item? Can a proposer check off items from the reviewer's list, or should the proposer be expected to respond with a comment, which the reviewer then audits before checking off from their own list?

**Comment by mushfs** [comment]
@jace Just testing..

- [ ] Please

- [ ] Do 

- [ ] This

**Comment by mushfs** [comment]
That's what I want, Reviewer creates Task list and Proposer ticks finished tasks. Works?

**Comment by jace** [comment]
Comments with task lists are supported, but there's no UI for checking them off.
