### ISSUE TITLE
Arbitrary HTML execution on "New ticket type" page using "Event name" as payload

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#535]
1. Visit **{profile}/{project}/events/new**
2. Supply payload (e.g. `<img src=x onerror=alert(1)>`) as title
3. Visit **{profile}/{project}/events/ticket_type/new** for payload execution

**Comment by jace** [comment]
Linked to this ancient bug in WTForms, the fix for which hasn't been released yet. We should monkey patch. https://github.com/wtforms/wtforms/issues/315

**Comment by jace** [comment]
Resolved in https://github.com/hasgeek/baseframe/pull/251 and https://github.com/hasgeek/baseframe/pull/252
