### ISSUE TITLE
Participant details are fetched through sequential numeric IDs instead of UUIDs

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#545]
As of now, participant details for a particular project can be fetched from the following URL:

```hasgeek.com/{profile}/{project}/participant/{id}/badge```
```hasgeek.com/{profile}/{project}/participant/{id}/edit```

```id``` takes sequential numbers as a value. ```id``` entries are linked to the overarching profile instead of the project, meaning that both ```{profile}/project-1/participant/1/badge``` and ```{profile}/project-2/participant/1/badge``` will fetch the same result.

This results in an IDOR issue, which can be used for fetching the details and/or badges of all participants under a given profile. To prevent enumeration of all given participants under a particular profile (the number of which can at times be sizable), UUID(s) should instead be used for fetching participant details.

**Comment by jace** [comment]
We shifted to UUIDs a few weeks ago. I don't have commit ids handy.
