### ISSUE TITLE
Hurdles in project navigation

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#553]
How and when do you get to know that you are a part of a project? Is there a section of the website that shows you the active projects you are a member of? Is there a way to find out whether you are part of a particular project without being provided a URL to it, or by discovering it through the homepage? A feature like this will be useful for those who are working on or are involved with multiple projects.

**Comment by jace** [comment]
Linked to #371 and #401. Once memberships are in place, the user's account page can show all projects and profiles they are affiliated with.

**Comment by jace** [comment]
Projects are now listed on a user's profile page.
