### ISSUE TITLE
Document terminology and features that first-time organizers are unacquainted with

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#561]
What is a tagline? Where does it show? What about a label? What a label meant to be used for when setting up a project?

These things will not be immediately apparent to anyone who has not received a walk-through of the platform from someone familiar with it. Therefore, help text should be added for each feature where terminology is not self-explanatory.

**Comment by jace** [comment]
Where is this supposed to happen?

**Comment by qurbat** [comment]
@jace In an earlier discussion with @vidya-ram I remember an info/pop-up box being suggested.

**Comment by jace** [comment]
Introducing vocabulary before the user experiences them is a bit like a movie showing credits at the beginning. It gets in the way of the experience, and you're not going to remember anyone. Better if characters are introduced when the story has built up to make space for them.

**Comment by jace** [comment]
Closing as this ticket is not actionable.
