### ISSUE TITLE
Remove defunct fields from edit project page

### ISSUE THREAD

**Issue by StephanieBr** [hasgeek/funnel#568]
Edit/New project form has fields which are obsolete. They need to be removed. 

- [x] Website form field (keep in db, remove from form)
- [x] Explore tab field
- [x] Background color field
- [x] Url to buy tickets field
- [x] Url name field  (tied to this issue - https://github.com/hasgeek/funnel/issues/497)

**Comment by jace** [comment]
@iambibhas explore tab URL needs to be removed from db as well. Possibly others. Migration necessary.
