### ISSUE TITLE
Defining permissions for accounts with unverified contact information

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#588]
As of now, users are able to create and use an account on the platform without having to verify their email address or phone number. Users are able to respond to RSVP for upcoming events, and submit/comment on session proposals. A lack of restrictions opens up the possibility for spam or junk content, which has been witnessed in the past.

While junk comments or proposals can be solved in other ways (such as adding nofollow #413, or by allowing users to report spam comments #520), it makes sense to attempt to fix the problem at an earlier level in the application's workflow. While it may not make sense to bar all functionality for accounts that lack verified contact information, at the very least, sufficient permissions and restrictions should explicitly be defined for them - while also not hindering user experience.

What should an unverified user account be able to do? This issue is intended receive input on and track the implementation of any such permission or restriction.

**Comment by jace** [comment]
From what I remember, a significant source of our spam is from accounts that (a) use Google accounts to login, and (b) pass the Recaptcha test.

**Comment by jace** [comment]
We no longer have _new_ unverified contact information since #1762. Older unverified email address will be processed for verification or removal. This ticket is no longer relevant.
