### ISSUE TITLE
Support for online events

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#589]
The platform is for the most part centered around in-person events. Though as the way that people participate in events and consume its content evolves, the need for introducing certain features (such as support for online events) arises. While it may be possible to use the platform to host an 'online only' event, changes new features are required to make the process easy and intuitive.

For instance, if an event is going to be hosted online - and a meeting link (for Jitsi, Zoom or Google Meet) is available with  the organizer - they should be able to add it as separate field which users can interact with instead of having to link to it in the 'about' section for the event. Other visual changes, such as featuring a 'WWW' icon instead of a pin-drop could perhaps be introduced as well. Also, as mentioned in #576, it would make sense for online events to be timezone-agnostic, given that all users would participate at the same time, rendering the definition of a 'project timezone' unnecessary and confusing. These changes could be perhaps supported with a radio button that allows an organizer to designating a particular event as being an 'online only' event.

This issue is intended to track pull requests which introduce or further online event support.

**Comment by jace** [comment]
Related: #606

**Comment by jace** [comment]
Projects can have a location without a venue from #606. Project timezone is pending deprecation in #576. Zoom links can be shared in pinned updates, where the editors have the ability to also describe it.

I'm closing this ticket as there's no independent ask here -- tracking tickets like this should be milestones.
