### ISSUE TITLE
Project location is redundant as location is available from venue

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#606]

**Comment by jace** [comment]
Counter proposal: keep the project location, as a text field is far simpler to work with than the elaborate Venue + Venue Room definition. The project location should also be the primary source shown on the home page card.

In addition:

1. Make Venue and Venue Room entirely optional to the schedule. Show the schedule even when no venue is displayed.

2. If the venue's location doesn't match the project location, show an alert to the editor/concierge asking if they want to update it. Use geonameid for the match.

**Comment by iambibhas** [comment]
Projects can have a `in_online` flag that can let each session have a livestream url instead of a room or venue. can that be fit into this somewhere?

**Comment by jace** [comment]
Read it off the location text field like in Hasjob. "Anywhere" there could be "Online" here. I expect it will diversify in future as people start specifying "Zoom", "Jitsi", etc.

**Comment by jace** [comment]
We are keeping `Project.location` as `Venue` is redundant in this online era.
