### ISSUE TITLE
Proposal transfers

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#62]
Owners of a proposal (`speaker_id` column if set, else `user_id`) can transfer proposals to any other user who has a Lastuser account. Funnel will make a holding account for them if they have never logged into Funnel before.

A user who has been assigned a proposal can also decline it, restoring ownership to the user who proposed it.

Caveats: Funnel will now have the same problem as HGTV: it won't be notified if the user edits their account without ever logging into Funnel.

TODO: Can Accept/Decline be a UI element? Can an assignment to another user be proposed without confirmation? Perhaps this requires a new `transferred_id` column that stores the user it has been transferred to until they accept it.

**Comment by shreyas-satish** [comment]
An urgent requirement is for the review team to transfer a proposal to a different user. Can we start with a simpler version of the above spec, where a review team member, can transfer a proposal to a given lastuser account without requiring the latter to confirm?

**Comment by jace** [comment]
Funnel can now benefit from automatic scope introduced in hasgeek/lastuser#166 in Feb 2016. There is no longer an AuthToken problem.

**Comment by jace** [comment]
Closed in #451.
