### ISSUE TITLE
RSVP modal improvements

### ISSUE THREAD

**Issue by StephanieBr** [hasgeek/funnel#694]
- [x] Desktop - ![Extra Large Copy@2x](https://user-images.githubusercontent.com/6479009/83408300-0a838b80-a430-11ea-9f6b-fc56e9b845d3.png)

- [x] Mobile -  ![Artboard](https://user-images.githubusercontent.com/6479009/83408409-2c7d0e00-a430-11ea-9d0e-e6f0966c8554.png)

- [x] Review copy

**Comment by vidya-ram** [comment]
Fixed in PR#699
