### ISSUE TITLE
Funnel - Ability to monitor the additions/deletions to funnel proposals

### ISSUE THREAD

**Issue by gnot** [hasgeek/funnel#8]
Scenario - 1. Event organizer - will be definitely interested in knowing addition & deletions to the funnel to provide feedback/validate. 
2. Event Attendee - interested folks would like to know new proposals which are getting added to help them make the right decision on attending (day/time slot) and possibly provide feedback/vote on the session. 
Suggestion - 
Notification - Mail would be ideal as it persists or a DM to twitter account with reference to the update. 
Duration/frequency - Daily would be ideal to minimize the traffic when herd comes in.

**Comment by jace** [comment]
A comprehensive notification system was introduced in #605. Also, it's been a while!
