### ISSUE TITLE
Public view  and voting of categorized proposals

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/funnel#80]
We now have the ability to set the status of Funnel proposal to either one of Submitted, Shortlisted, Confirmed, Waitlisted, Rejected.

However, this still does not reflect on the UI for non-admins.

For each of these statuses, we need to determine whether or not it should be explicitly shown to non-admins on (1) the proposal space page (2) the proposal page itself.

We also need to determine whether we should allow voting for rejected proposals.

**Comment by jace** [comment]
Voting was removed long ago, and hardcoded proposal states are pending removal in #91. Also, hi! Long time!
