### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by arundhaj** [hasgeek/funnel#97]
When requesting "http://in.pycon.org/funnel/2014/json" from different domain, browser prevents the request with following error.

```
XMLHttpRequest cannot load http://in.pycon.org/funnel/2014/json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://codepen.io' is therefore not allowed access. 
```

I checked the same for https://funnel.hasgeek.com/fifthel2014/json and ended up with the same issue.

Adding the appropriate "Access-Control-Allow-Origin" header to the response would solve this.

**Comment by jace** [comment]
The JSON endpoint was removed recently as there is no current usage of the feature. We instead have JSON support in most regular endpoints, and with a pending spec for a stable JSON data API (pending because there's no current demand).
